---
- name: Docker | Install apt dependencies for ansible apt
  apt:
    pkg: "{{ item }}"
    state: latest
  with_items:
    - python-apt
    - apt-transport-https
    - ca-certificates
    - gnupg2
  become: yes

- name: Docker | Add docker apt key
  apt_key:
    keyserver: 'ha.pool.sks-keyservers.net'
    id: 58118E89F3A912897C070ADBF76221572C52609D
    state: present
  become: yes
 
- name: Docker | Add docker debian jessie apt repository
  apt_repository:
    repo: 'deb https://apt.dockerproject.org/repo debian-jessie main'
    state: present
  become: yes
 
- name: Docker | Make sure docker and its dependencies are installed
  apt:
    pkg: docker-engine
    state: present
  become: yes
